version: '2.1'
services:
  app:
    build: .
    working_dir: /code
    volumes:
      - .:/code
    environment:
      - POSTGRESQL_PASSWORD=devel
      - POSTGRESQL_USER=devel
      - POSTGRESQL_DB=devel
      #- POSTGRESQL_HOST=postgresql
      #- PYTHONPATH=.
    # links:
    #   - postgresql:postgresql
    ports:
      - "8000:8000"
    entrypoint:  /code/docker/entrypoint.sh
  postgresql:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=devel
      - POSTGRES_USER=devel
      - POSTGRES_DB=devel
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local