# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-31 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0002_auto_20170611_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('books', models.ManyToManyField(to='shelf.Book')),
            ],
        ),
    ]
