# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-05 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0003_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='books',
            field=models.ManyToManyField(related_name='books', to='shelf.Book'),
        ),
    ]
