# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-05 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0004_auto_20170905_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_nice',
            field=models.BooleanField(default=False, verbose_name='is nice ?'),
        ),
    ]
